### ISSUE TITLE
Failed to open the file: assets/shaders/world_opaque.frag

### ISSUE THREAD

**Issue by PEKEW** [Isti01/glCraft#4]
Hi, Regardless of whether I use CMake or CLion, I get the same error: "Failed to open the file: assets/shaders/world_opaque.frag." However, when I checked the build folder, I found that the file path does exist. I'm not sure if this is a permission issue causing the problem.

**Comment by Isti01** [comment]
Hi! Could you verify the working directory the game is running in please?

**Comment by PEKEW** [comment]
> Hi! Could you verify the working directory the game is running in please?

thx for your replay, I get this `"C:\\Users\\admin\\Desktop\\glCraft\\cmake-build-debug"` when I add
```C++ 
 std::filesystem::path currentPath = std::filesystem::current_path();
  std::cout << currentPath << std::endl;
``` 
in main (with Clion)

**Comment by Isti01** [comment]
Interesting, some people had issues with symlinks. Could you try manually copying the `assets` folder into `cmake-build-debug`, please? If that fixes the issue we can confirm that it is related to using symlinks.

**Comment by PEKEW** [comment]
When I reconfigured the asset files in CLion, everything compiled and ran fine. 
However, when I attempted to manually build, the problem still exists， and the solution is to move "Build/assets" to "Build/Debug/assets". I'm not sure why Clion and manual CMake behave differently. I apologize for not being very familiar with this toolchain. Another interesting discovery is that, although Clion can make the program run correctly, its symlink file seem to be not quite right.
![image](https://github.com/Isti01/glCraft/assets/98371836/dde45307-2bda-4db6-a980-965783cd4bf4)
But the file which I manually generate is right:
![image](https://github.com/Isti01/glCraft/assets/98371836/197ce1f6-b781-42b8-89af-320b3c9bc686)

**Comment by Isti01** [comment]
Interesting, Clion might using a different version of CMake, because JetBrains ships it with a bundled one.
I don't know what else could be different when you are running it manually. 

Try replacing the command that creates a symlink with a command that copies the files, like this:

Open CMakeLists.txt and replace the last command (it has the word `create_symlink`) with this:
```
file(COPY ${CMAKE_SOURCE_DIR}/assets DESTINATION ${CMAKE_CURRENT_BINARY_DIR})
```

**Comment by Isti01** [comment]
You might need to delete the assets symlink before doing this

**Comment by PEKEW** [comment]
now it works well :
```
# set a copy command for the assets dir
file(COPY ${CMAKE_SOURCE_DIR}/assets DESTINATION ${CMAKE_BINARY_DIR}/Debug)

# or create a symbolic link
#execute_process(
#   COMMAND ${CMAKE_COMMAND} -E create_symlink
#  ${CMAKE_SOURCE_DIR}/assets ${CMAKE_BINARY_DIR}/Debug/assets
#)
````

**Comment by Isti01** [comment]
I'm glad it worked
